# Generated by Django 3.2.9 on 2021-11-08 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name_pattern', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='name_pattern',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='heading',
            name='name_pattern',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Item_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name_pattern', models.CharField(max_length=100, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brand')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
